# get single room
### 
GET http://localhost:5000/api/rooms/69d3bec255958d52ab66fd17

# get rooms
###
GET http://localhost:5000/api/rooms/

# create room
###
POST http://localhost:5000/api/rooms
Content-Type: application/json
 
{
    "name": "Lenin room",
    "price": 4500,
    "desc": "Stalin",
    "roomNumbers": [{
        "number": 102,              
        "unavailableDates": ["2024-01-24","2024-01-26"]
    }]
}


# update room
###
PUT http://localhost:5000/api/rooms/69d3db4f3d704cdf9c049e7f
Content-Type: application/json
 
{
    "name": "Lenin room",
    "price": 3200  
}

# delete room
###
DELETE  http://localhost:5000/api/rooms/69d3db8d3d704cdf9c049e8e

# get bookings
### 
GET http://localhost:5000/api/bookings

# get single booking
### 
GET http://localhost:5000/api/bookings/6906773e23a894dc54456118

# post booking
### 
POST http://localhost:5000/api/bookings
Content-Type: application/json

{
  "roomId": "690675bca63fbaf8467608e5",
  "name": "damiao",
  "email": "aloi@gmail.com",
  "checkInDate": "2025-11-15",
  "checkOutDate": "2025-11-18"
}


# update booking
###
PUT http://localhost:5000/api/bookings/6906776cc32a0a112adeec87
Content-Type: application/json
 
{
    "name": "Stalin",
    "email": "Stalin@gmail.com"
}

# delete booking
###
DELETE http://localhost:5000/api/bookings/699c559d96e7d7072b934a28

#get users
###
GET http://localhost:5000/api/users

#create user
###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "Lenin",
    "email": "lenin@gmail.com",
    "password": "81312192"
}

# update user
###
PUT http://localhost:5000/api/users/6994702bab056b4165c62b73
Content-Type: application/json

 {
    "email": "johnny.8131@gmail.com"
}

# delete user
###
DELETE  http://localhost:5000/api/users/699c56456d95ea92b68236ee

# login user
###
POST http://localhost:5000/api/users/login
Content-Type: application/json

 {
       "email": "lenin@gmail.com",
    "password": "81312192"
}

#check auth
###
GET http://localhost:5000/auth

#logout user
###
POST http://localhost:5000/api/users/logout